"use client";
import dynamic from 'next/dynamic';
import { ThemeProvider, createTheme } from '@mui/material/styles'
import './globals.css'
import { Box, Stack } from "@mui/material"

// -----------------------------------------------------------------------------------

const Header = dynamic(() => import('@/components/Header'))
const Footer = dynamic(() => import('@/components/Footer'))

const theme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#FD7C1E'
    }
  },
  typography: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 18
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          textTransform: 'none',
          color: 'white'
        }
      }
    }
  }
})

// -----------------------------------------------------------------------------------

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// -----------------------------------------------------------------------------------

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <ThemeProvider theme={theme}>
          <Stack sx={{ minHeight: '100vh' }}>
            <Header />
            <Box flexGrow={1}>
              {children}
            </Box>
            <Footer />
          </Stack>
        </ThemeProvider>
      </body>
    </html>
  )
}
